version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db
    volumes:
      - wordpress:/var/www/html
      - ${THEMES_DIR:-./wp-content/themes}:/var/www/html/wp-content/themes
      - ${PLUGINS_DIR:-./wp-content/plugins}:/var/www/html/wp-content/plugins
      - ${UPLOADS_DIR:-./wp-content/uploads}:/var/www/html/wp-content/uploads

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: